### ISSUE TITLE
Support for non-canonical contigs?

### ISSUE THREAD

**Issue by bioinformed** [Genomicsplc/variantkey#26]
Many genes and variants occur on chromosomes other than 1-22, X, Y, Mt.  Any serious research or clinical use will need to include support for these, which raises questions on the longevity and applicability of the currently proposed number of bits allocated to storing contig/chromosome.

**Comment by nicolaasuni** [comment]
Hi, thank you for your question.

Given the 64 bit limit, VariantKey has been mainly designed to deal with human genetic variants that occur on canonical chromosomes 1-22, X, Y and MT. However, the CHROM section in the VariantKey model is 5 bit, so it can represent 32 different values.

CHROM values from 26 to 31 are currently reserved. They will be used to indicate 6 alternative modes to interpret the remaining 59 bit. One of these values can be used to indicate the encoding of variants that occurs in non-canonical contigs.

When the number of bit is not enough to directly represent all the variant information, VariantKey can be used as non-reversible hash code that is unique for each variant. This allows, for instance, to deal with variants in a database as single numerical entities. A lookup table can be used to reverse the hash-code-type VariantKeys.

**Comment by bioinformed** [comment]
The current GRCh38 human reference genome contains 42 unplaced contigs, 127 unmapped contigs, and 264 alternative contigs.  So too many bits to use without a coordinate transformation or some other trick to pack more information into those few extra values.

I'm not advocating for any particular solution -- just making sure that I understand the scope and limitations of the proposed format.

Also, have you given any thought to versioning?  What happens when the next reference genome build or patch is released?

**Comment by nicolaasuni** [comment]
The CHROM section can't be used to directly encode the non-canonical contigs, but it can be used to indicate 6 extra encoding schema for the remaining 59 bit. When a variant has too much information to be packed in 59 bit  we can encode the whole or parts of it as hash code.

> Also, have you given any thought to versioning? What happens when the next reference genome build or patch is released?

VariantKey doesn't generate universal codes, it only encodes CHROM, POS, REF and ALT, so each code is unique for a given reference genome. The direct comparisons of two VariantKeys makes sense only if they both refer to the same genome reference.
